apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: harvester
  namespace: kube-system
spec:
  valuesContent: |-
    kube-vip:
      config:
        vip_interface: "bond0"
    service:
      vip:
        enabled: true
        mode: "{{ .VipMode }}"
        ip: "{{ .Vip }}"
        hwAddress: "{{ .VipHwAddr }}"
